# golangci-lint configuration for stipple
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/cboone/stipple

linters:
  enable:
    # Quality
    - bodyclose
    - durationcheck
    - errcheck
    - gocritic
    - gocyclo
    - nilerr
    - revive
    # Style
    - godot

  settings:
    gocyclo:
      min-complexity: 15

    godot:
      capital: false
      scope: declarations

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: var-declaration
        - name: var-naming
