# goreleaser configuration for stipple
# https://goreleaser.com

version: 2

# stipple is a library, not a binary
builds:
  - skip: true

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Tests
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: Build
      regexp: '^.*?(build|ci)(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: Other
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^style:"

release:
  header: |
    ## stipple {{ .Tag }}

    A braille graphics rendering library for Go.

    ### Installation

    ```bash
    go get github.com/cboone/stipple@{{ .Tag }}
    ```
  footer: |
    **Full Changelog**: https://github.com/cboone/stipple/compare/{{ .PreviousTag }}...{{ .Tag }}
