name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: cboone/gh-actions/.github/workflows/run-go-ci.yml@844bf31d4ec26df9d0aa531e79d8c3fccf9f0638 # v3.1.0
    with:
      run-lint: true
      run-build: true
      run-format-check: true
