name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    uses: cboone/gh-actions/.github/workflows/release-go-binaries.yml@844bf31d4ec26df9d0aa531e79d8c3fccf9f0638 # v3.1.0
